#FROM openbxi/centos-bxibase-jupyter-c:latest
FROM openbxi/alpine-bxibase-jupyter:latest
MAINTAINER "Pierre Vignéras" <pierre.vigneras@atos.net>

ADD resources/* /srv/
RUN chown -R fantom:users /srv/
