FROM local/centos-jupyter-c:latest
MAINTAINER "Pierre Vignéras" <pierre.vigneras@atos.net>

RUN     echo $'[local] \n\
name=Local \n\
baseurl=file:///rpms \n\
enabled=1 \n\
gpgcheck=0 \n\
protect=1 \n'\
> /etc/yum.repos.d/local.repo


RUN yum -y install bxibase
