FROM centos:7
MAINTAINER "Pierre Vignéras" <pierre.vigneras@atos.net>

RUN rpm -iUvh http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm && yum -y update && yum -y clean all

CMD ["/bin/bash"]

