FROM local/centos-jupyter:latest
MAINTAINER "Pierre Vignéras" <pierre.vigneras@atos.net>

RUN sudo -E yum --assumeyes install git
RUN wget -O - https://raw.githubusercontent.com/brendan-rius/jupyter-c-kernel/master/install.sh | sudo -E sh  
RUN sudo -E sed -i "s/'-std=c11'/'-std=c11', '-lbxibase', '-D_POSIX_C_SOURCE=200809L'/g" /usr/lib/python3.4/site-packages/jupyter_c_kernel/kernel.py

