FROM openbxi/centos-bxibase:latest
MAINTAINER "Pierre Vignéras" <pierre.vigneras@atos.net>

RUN yum --assumeyes upgrade && \
    yum --assumeyes install gcc python-pip python-devel && \
    pip install --upgrade pip && \
    pip install jupyter && \
    yum --assumeyes erase gcc python-pip python-devel && \
    package-cleanup --leaves --all 

# Create the fantom user
RUN useradd -u 1000 -g users -G wheel -m fantom

# Trust the wheel groop by default for su & sudo
RUN sed -i '/^#auth.*pam_wheel.so.*trust /s/^#//' /etc/pam.d/su && \
    echo '%wheel ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

WORKDIR /home/fantom
USER fantom


RUN echo $'#!/bin/bash\n\
/usr/bin/jupyter notebook --ip='*' --port=8080 --NotebookApp.token='' --notebook-dir=/srv --NotebookApp.default_url=notebooks/index.ipynb --NotebookApp.open_browser=False --no-browser'\
>> /home/fantom/jupyter-wrapper.sh && chmod +x /home/fantom/jupyter-wrapper.sh

#RUN cat /home/fantom/jupyter-wrapper.sh

CMD /home/fantom/jupyter-wrapper.sh
EXPOSE 80